# Generated by Django 6.0.1 on 2026-01-08 04:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_is_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit phone number', regex='^[6-9]\\d{9}$')]),
        ),
    ]
